### ISSUE TITLE
关于常量的定义

### ISSUE THREAD

**Issue by Zentopia** [astaxie/build-web-application-with-golang#882]
文中说"所谓常量，也就是在程序编译阶段就确定下来的值，而程序在运行时无法改变该值。", 动态语言的常量应该怎么定义呢

**Comment by chenyihui555** [comment]
同问?

**Comment by yjhmelody** [comment]
编译型语言的常量是靠编译时的检查来控制其不能改变的。
解释型语言的常量靠解释器运行时的检查来约束的。
比如JS
```js
> const num = 1
undefined
> num = 2
TypeError: Assignment to constant variable.
    at repl:1:5
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:440:10)
    at emitOne (events.js:120:20)
    at REPLServer.emit (events.js:210:7)
    at REPLServer.Interface._onLine (readline.js:279:10)
    at REPLServer.Interface._line (readline.js:626:8)
```
@Zentopia 
@chenyihui555
